
SELECT COUNT(a.Sid) AS Total_lectures, SUM(CASE WHEN a.Present = 'present' THEN 1 ELSE 0 END) AS Total_present, SUM(CASE WHEN a.Present = 'absent' THEN 1 ELSE 0 END) AS Total_absent, ROUND((SUM(CASE WHEN a.Present = 'present' THEN 1 ELSE 0 END) * 100) / (SUM(CASE WHEN a.Present = 'present' THEN 1 ELSE 0 END) + SUM(CASE WHEN a.Present = 'absent' THEN 1 ELSE 0 END)), 2) AS Attendance_percent FROM ATTENDANCE a, SUBJECT sub WHERE a.Sid = 'DE21648' AND a.Subject_code = sub.Subject_code;

SELECT s.*, COUNT(a.Sid) AS Total_lectures, SUM(CASE WHEN a.Present = 'present' THEN 1 ELSE 0 END) AS Total_present, SUM(CASE WHEN a.Present = 'absent' THEN 1 ELSE 0 END) AS Total_absent, ROUND((SUM(CASE WHEN a.Present = 'present' THEN 1 ELSE 0 END) * 100) / (SUM(CASE WHEN a.Present = 'present' THEN 1 ELSE 0 END) + SUM(CASE WHEN a.Present = 'absent' THEN 1 ELSE 0 END)), 2) AS Attendance_percent FROM STUDENT s, ATTENDANCE a, SUBJECT sub WHERE a.Sid = 'DE21648' AND a.Sid = s.Sid AND a.Subject_code = sub.Subject_code;

SELECT a.Sid, COUNT(a.Sid) AS Total_lectures, SUM(CASE WHEN a.Present = 'present' THEN 1 ELSE 0 END) AS Total_present, SUM(CASE WHEN a.Present = 'absent' THEN 1 ELSE 0 END) AS Total_absent, ROUND((SUM(CASE WHEN a.Present = 'present' THEN 1 ELSE 0 END) * 100) / (SUM(CASE WHEN a.Present = 'present' THEN 1 ELSE 0 END) + SUM(CASE WHEN a.Present = 'absent' THEN 1 ELSE 0 END)), 2) AS Attendance_percent FROM STUDENT s, ATTENDANCE a, SUBJECT sub WHERE EXISTS (SELECT * FROM STUDENT s2 WHERE a.Sid = s2.Sid AND a.Sid = s.Sid AND a.Subject_code = sub.Subject_code) GROUP BY a.Sid;

SELECT s.*, a.Sid AS Asid, COUNT(a.Sid) AS Total_lectures, SUM(CASE WHEN a.Present = 'present' THEN 1 ELSE 0 END) AS Total_present, SUM(CASE WHEN a.Present = 'absent' THEN 1 ELSE 0 END) AS Total_absent, ROUND((SUM(CASE WHEN a.Present = 'present' THEN 1 ELSE 0 END) * 100) / (SUM(CASE WHEN a.Present = 'present' THEN 1 ELSE 0 END) + SUM(CASE WHEN a.Present = 'absent' THEN 1 ELSE 0 END)), 2) AS Attendance_percent FROM STUDENT s, ATTENDANCE a, SUBJECT sub WHERE EXISTS (SELECT * FROM STUDENT s2 WHERE s2.Sid = s.Sid AND a.Sid = s2.Sid AND a.Sid = s.Sid AND a.Subject_code = sub.Subject_code) GROUP BY a.Sid;

SELECT s.*, a.Sid AS Asid, COUNT(a.Sid) AS Total_lectures, SUM(CASE WHEN a.Present = 'present' THEN 1 ELSE 0 END) AS Total_present, SUM(CASE WHEN a.Present = 'absent' THEN 1 ELSE 0 END) AS Total_absent, ROUND((SUM(CASE WHEN a.Present = 'present' THEN 1 ELSE 0 END) * 100) / (SUM(CASE WHEN a.Present = 'present' THEN 1 ELSE 0 END) + SUM(CASE WHEN a.Present = 'absent' THEN 1 ELSE 0 END)), 2) AS Attendance_percent FROM STUDENT s, ATTENDANCE a, SUBJECT sub WHERE EXISTS (SELECT * FROM STUDENT s2 WHERE s2.Sid = s.Sid AND a.Sid = s.Sid AND a.Subject_code = sub.Subject_code) GROUP BY a.Sid;

SELECT DISTINCT s.*, IF(a.Sid = s.Sid, a.Sid, NULL) AS Asid FROM STUDENT s, ATTENDANCE a WHERE EXISTS (SELECT * FROM STUDENT s2 WHERE s.Sid = s2.Sid);
