SELECT a.Subject_code, SUM(CASE WHEN a.Status = 'present' THEN 1 ELSE 0 END) AS Total_present, SUM(CASE WHEN a.Status = 'absent' THEN 1 ELSE 0 END) AS Total_absent, ROUND((SUM(CASE WHEN a.Status = 'present' THEN 1 ELSE 0 END) * 100) / (SUM(CASE WHEN a.Status = 'present' THEN 1 ELSE 0 END) + SUM(CASE WHEN a.Status = 'absent' THEN 1 ELSE 0 END)), 2) AS Attendance_percent FROM ATTENDANCE a, SUBJECT sub WHERE a.Sid = 'DE21648' AND a.Subject_code = sub.Subject_code GROUP BY a.Subject_code, sub.Subject_code;

SELECT a.Subject_code, SUM(CASE WHEN a.Status = 'present' THEN 1 ELSE 0 END) AS Total_present, SUM(CASE WHEN a.Status = 'absent' THEN 1 ELSE 0 END) AS Total_absent, ROUND((SUM(CASE WHEN a.Status = 'present' THEN 1 ELSE 0 END) * 100) / (SUM(CASE WHEN a.Status = 'present' THEN 1 ELSE 0 END) + SUM(CASE WHEN a.Status = 'absent' THEN 1 ELSE 0 END)), 2) AS Attendance_percent FROM ATTENDANCE a, SUBJECT sub WHERE a.Sid = 'DE21648' AND a.Subject_code = sub.Subject_code GROUP BY a.Subject_code, sub.Subject_code;

SELECT a.Subject_code, COUNT(a.Subject_code) AS Total_lectures, SUM(CASE WHEN a.Status = 'present' THEN 1 ELSE 0 END) AS Total_present, SUM(CASE WHEN a.Status = 'absent' THEN 1 ELSE 0 END) AS Total_absent, ROUND((SUM(CASE WHEN a.Status = 'present' THEN 1 ELSE 0 END) * 100) / (SUM(CASE WHEN a.Status = 'present' THEN 1 ELSE 0 END) + SUM(CASE WHEN a.Status = 'absent' THEN 1 ELSE 0 END)), 2) AS Attendance_percent FROM ATTENDANCE a, SUBJECT sub WHERE a.Sid = 'DE21648' AND a.Subject_code = sub.Subject_code GROUP BY a.Subject_code, sub.Subject_code;

SELECT t1.*, t2.*, ROUND(((Total_lectures * 100) / Attendance_ratio), 2) AS Attendance_ratio_in_percent FROM (SELECT a.Subject_code, COUNT(a.Subject_code) AS Total_lectures, SUM(CASE WHEN a.Status = 'present' THEN 1 ELSE 0 END) AS Total_present, SUM(CASE WHEN a.Status = 'absent' THEN 1 ELSE 0 END) AS Total_absent, ROUND((SUM(CASE WHEN a.Status = 'present' THEN 1 ELSE 0 END) * 100) / (SUM(CASE WHEN a.Status = 'present' THEN 1 ELSE 0 END) + SUM(CASE WHEN a.Status = 'absent' THEN 1 ELSE 0 END)), 2) AS Attendance_percent FROM ATTENDANCE a, SUBJECT sub WHERE a.Sid = 'DE21648' AND a.Subject_code = sub.Subject_code GROUP BY a.Subject_code, sub.Subject_code) AS t1, (SELECT SUM(Total_lectures) AS Attendance_ratio FROM (SELECT a.Subject_code, COUNT(a.Subject_code) AS Total_lectures, SUM(CASE WHEN a.Status = 'present' THEN 1 ELSE 0 END) AS Total_present, SUM(CASE WHEN a.Status = 'absent' THEN 1 ELSE 0 END) AS Total_absent, ROUND((SUM(CASE WHEN a.Status = 'present' THEN 1 ELSE 0 END) * 100) / (SUM(CASE WHEN a.Status = 'present' THEN 1 ELSE 0 END) + SUM(CASE WHEN a.Status = 'absent' THEN 1 ELSE 0 END)), 2) AS Attendance_percent FROM ATTENDANCE a, SUBJECT sub WHERE a.Sid = 'DE21648' AND a.Subject_code = sub.Subject_code GROUP BY a.Sid, a.Subject_code, sub.Subject_code) AS t11) AS t2;

SELECT t1.*, ROUND(((Total_lectures_in_subject * 100) / Total_lectures), 2) AS Attendance_percent FROM (SELECT a.Sid, a.Subject_code, COUNT(a.Subject_code) AS Total_lectures_in_subject, SUM(CASE WHEN a.Status = 'present' THEN 1 ELSE 0 END) AS Total_present, SUM(CASE WHEN a.Status = 'absent' THEN 1 ELSE 0 END) AS Total_absent, ROUND((SUM(CASE WHEN a.Status = 'present' THEN 1 ELSE 0 END) * 100) / (SUM(CASE WHEN a.Status = 'present' THEN 1 ELSE 0 END) + SUM(CASE WHEN a.Status = 'absent' THEN 1 ELSE 0 END)), 2) AS Attendance_percent_in_subject FROM ATTENDANCE a, SUBJECT sub WHERE a.Subject_code = sub.Subject_code GROUP BY a.Sid, a.Subject_code, sub.Subject_code) AS t1, (SELECT t11.Sid, SUM(Total_lectures_in_subject) AS Total_lectures FROM (SELECT a.Sid, a.Subject_code, COUNT(a.Subject_code) AS Total_lectures_in_subject, SUM(CASE WHEN a.Status = 'present' THEN 1 ELSE 0 END) AS Total_present, SUM(CASE WHEN a.Status = 'absent' THEN 1 ELSE 0 END) AS Total_absent, ROUND((SUM(CASE WHEN a.Status = 'present' THEN 1 ELSE 0 END) * 100) / (SUM(CASE WHEN a.Status = 'present' THEN 1 ELSE 0 END) + SUM(CASE WHEN a.Status = 'absent' THEN 1 ELSE 0 END)), 2) AS Attendance_percent_in_subject FROM ATTENDANCE a, SUBJECT sub WHERE a.Subject_code = sub.Subject_code GROUP BY a.Sid, a.Subject_code, sub.Subject_code) AS t11 GROUP BY t11.Sid) AS t2 WHERE t1.Sid = t2.Sid AND t1.Sid = 'DE21648';
